# Generated by Django 3.1.7 on 2021-03-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covercallbacktest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covercallbacktest',
            old_name='volatility',
            new_name='expirationPrice',
        ),
    ]
