# Generated by Django 3.1.7 on 2021-03-27 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covercallbacktest', '0002_auto_20210327_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covercallbacktest',
            old_name='expirationPrice',
            new_name='endPrice',
        ),
    ]
