# Generated by Django 3.1.7 on 2021-03-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covercallbacktest', '0003_auto_20210327_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=10)),
                ('closePrice', models.FloatField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='covercallbacktest',
            name='endPrice',
        ),
    ]
