# Generated by Django 3.1.7 on 2021-03-27 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covercallbacktest', '0004_auto_20210328_0203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClosePrice',
        ),
    ]
