# Generated by Django 3.1.7 on 2021-03-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='closePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.TextField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='coverCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetPrice', models.DecimalField(decimal_places=10, max_digits=19)),
                ('strikePrice', models.DecimalField(decimal_places=10, max_digits=19)),
                ('maturity', models.DecimalField(decimal_places=10, max_digits=19)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=19)),
                ('volatility', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
    ]
