# Generated by Django 3.1.7 on 2021-03-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covercall', '0002_auto_20210322_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('symbol', models.CharField(max_length=10)),
                ('closePrice', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoverCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetPrice', models.FloatField(null=True)),
                ('strikePrice', models.FloatField(null=True)),
                ('maturity', models.FloatField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('volatility', models.FloatField(null=True)),
                ('optionsPrice', models.FloatField(null=True)),
                ('numberStock', models.IntegerField()),
                ('numberOption', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ClosePrice1',
        ),
        migrations.DeleteModel(
            name='CoverCall1',
        ),
    ]
