# Generated by Django 3.1.7 on 2021-03-23 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covercall', '0004_auto_20210322_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covercall',
            name='numberOption',
        ),
        migrations.RemoveField(
            model_name='covercall',
            name='numberStock',
        ),
        migrations.RemoveField(
            model_name='covercall',
            name='optionsPrice',
        ),
    ]
