# Generated by Django 3.1.7 on 2021-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covercall', '0006_remove_covercall_volatility'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverCallStrate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assetPrice', models.FloatField(null=True)),
                ('strikePrice', models.FloatField(null=True)),
                ('maturity', models.FloatField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CoverCall',
        ),
    ]
