# Generated by Django 3.0.2 on 2021-04-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covercall', '0008_cwprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverCallBt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdateBt', models.DateField()),
                ('enddateBt', models.DateField()),
                ('timerange', models.FloatField(null=True)),
                ('c', models.FloatField(null=True)),
                ('m', models.FloatField(null=True)),
                ('n', models.FloatField(null=True)),
                ('s', models.FloatField(null=True)),
            ],
        ),
    ]
