# Generated by Django 3.0.2 on 2021-04-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covercall', '0009_covercallbt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covercallbt',
            name='s',
        ),
    ]
