# Generated by Django 3.0.2 on 2021-04-28 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covercall', '0010_remove_covercallbt_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covercallbt',
            name='startdateBt',
        ),
    ]
