# Generated by Django 3.0.2 on 2021-04-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covercall', '0011_remove_covercallbt_startdatebt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverCallBacktest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdateBt', models.DateField()),
                ('enddateBt', models.DateField()),
                ('timerange', models.FloatField(null=True)),
                ('c', models.FloatField(null=True)),
                ('m', models.FloatField(null=True)),
                ('n', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CoverCallBt',
        ),
    ]
