# Generated by Django 3.0.2 on 2021-05-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covercall', '0013_backtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackTestCovered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enddateBt', models.DateField()),
                ('timerange', models.FloatField(null=True)),
                ('rate', models.FloatField(null=True)),
                ('strikePrice', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Backtest',
        ),
    ]
