# Generated by Django 3.0.2 on 2021-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covercall', '0015_auto_20210501_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestcover',
            name='maturity',
            field=models.FloatField(default=0.5),
        ),
    ]
