# Generated by Django 3.0.2 on 2021-05-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covercall', '0016_backtestcover_maturity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackTester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enddateBt', models.DateField()),
                ('timerange', models.FloatField(null=True)),
                ('m', models.FloatField(null=True)),
                ('n', models.FloatField(null=True)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
    ]
